### ISSUE TITLE
Add preprocess support to cryodrgn backproject_voxel

### ISSUE THREAD

**Issue by jianghaizhu** [zhonge/cryodrgn#108]
**Describe the bug**
Using version 0.3.4 to preprocess data to 128x128, I end up with an image stack of size 129x129.

**To Reproduce**
cryodrgn preprocess cryosparc_P1_J22_008_particles.cs --datadir data/ori -D 128 -o data/preprocessed/particles_128.mrcs

**Expected behavior**
An image stack of size 128x128 pixel.

**Additional context**
Here is the output of the command.

2022-02-22 12:33:11     Loading 271288 280x280 images
2022-02-22 12:33:11     Downsampling images to 128x128
2022-02-22 12:33:11     Processing chunk 1 of 3
2022-02-22 12:33:11     Processing batch of 5000 images (1 of 20)
2022-02-22 12:34:25     Processing batch of 5000 images (2 of 20)
2022-02-22 12:35:26     Processing batch of 5000 images (3 of 20)
2022-02-22 12:36:49     Processing batch of 5000 images (4 of 20)
2022-02-22 12:37:51     Processing batch of 5000 images (5 of 20)
2022-02-22 12:38:53     Processing batch of 5000 images (6 of 20)
2022-02-22 12:40:05     Processing batch of 5000 images (7 of 20)
2022-02-22 12:41:09     Processing batch of 5000 images (8 of 20)
2022-02-22 12:42:15     Processing batch of 5000 images (9 of 20)
2022-02-22 12:43:19     Processing batch of 5000 images (10 of 20)
2022-02-22 12:44:22     Processing batch of 5000 images (11 of 20)
2022-02-22 12:45:30     Processing batch of 5000 images (12 of 20)
2022-02-22 12:46:32     Processing batch of 5000 images (13 of 20)
2022-02-22 12:47:38     Processing batch of 5000 images (14 of 20)
2022-02-22 12:49:01     Processing batch of 5000 images (15 of 20)
2022-02-22 12:50:31     Processing batch of 5000 images (16 of 20)
2022-02-22 12:51:55     Processing batch of 5000 images (17 of 20)
2022-02-22 12:53:06     Processing batch of 5000 images (18 of 20)
2022-02-22 12:54:18     Processing batch of 5000 images (19 of 20)
2022-02-22 12:55:29     Processing batch of 5000 images (20 of 20)
2022-02-22 12:56:49     New shape: (100000, 129, 129)

**Comment by zhonge** [comment]
This is expected behavior -- it is part of the preprocessing shortcut to save out an intermediate form of the particles (Hartley representation, normalized, FFT-symmetrized), which reduces memory usage later on. It does mean that you can't use these particles for anything else other than as input to `cryodrgn train_vae` with the `--preprocessed` flag.

**Comment by jianghaizhu** [comment]
Ok, thanks for the explanation. It would be nice to print out a message to ease the user's confusion. Also, one of the drawbacks is that I cannot generate a volume using "cryodrgn backproject_vol" anymore since the image size is not even.

**Comment by jianghaizhu** [comment]
I found another potential bug. After preprocessing with image size of 129x129, I have no problem to train the model with "cryodrgn train_vae data/preprocess/particles_128.ft.txt --preprocessed --ctf data/ctf.pkl --poses data/pose.pkl --zdim 8 -n 50 --multigpu --amp -o 00_vae128_z8". 

However, if I use "cryodrgn train_vae data/preprocess/particles_128.ft.txt --preprocessed --ctf data/ctf.pkl --poses data/pose.pkl --zdim 8 -n 50 --multigpu --amp -o 00_vae128_z8 --lazy", I got the following error.

Traceback (most recent call last):
  File "/opt/conda/envs/cryoDRGN/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.4', 'console_scripts', 'cryodrgn')())
  File "/opt/conda/envs/cryoDRGN/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/__main__.py", line 54, in main
    args.func(args)
  File "/opt/conda/envs/cryoDRGN/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/commands/train_vae.py", line 314, in main
    data = dataset.LazyMRCData(args.particles, norm=args.norm, invert_data=args.invert_data, ind=ind, keepreal=args.use_real, window=args.window, datadir=args.datadir, relion31=args.relion31, window_r=args.window_r)
  File "/opt/conda/envs/cryoDRGN/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/dataset.py", line 52, in __init__
    assert ny % 2 == 0, "Image size must be even"
AssertionError: Image size must be even

I don't have to use "--lazy" when I am training the small model. But I have to use it when I am training a big model with size of 256x256 or actually 257x257 since I don't have enough memory to load all images at once. Now because of this "Image size must be even" error, I cannot train my big model.
