### ISSUE TITLE
Memory Allocation Issue

### ISSUE THREAD

**Issue by mttdoran** [zhonge/cryodrgn#111]
I am working with a dataset of ~200,000 particles that I have downsampled 2x to 240 pixels. After downsampling, I reprojected the particle stack and obtained a good reconstruction of our complex. When initiating training I use the command:

cryodrgn train_vae cryoDRGN/dwnsmpl_cryodrgn_particles.mrcs --ctf cryoDRGN/ctf.pkl --poses cryoDRGN/poses.pkl --zdim 8 -n 25 --relion31 -b 1 --multigpu --lazy -o cryoDRGN/train240 > training.log

Even after indicating a batch size of 1 as well as the --lazy flags, I am receiving this error:

RuntimeError: CUDA out of memory. Tried to allocate 9.07 GiB (GPU 0; 15.78 GiB total capacity; 9.14 GiB already allocated; 5.22 GiB free; 9.14 GiB reserved in total by PyTorch)

I was wondering if there are further flags that could reduce the memory allocation or any suggestions that could enable the run to complete. 

I have tried running these jobs on 1-4 V100s and P100s.

Thank you!

**Comment by 2subzero** [comment]
I am having the same issue so tagging along.

`RuntimeError: CUDA out of memory. Tried to allocate 18.14 GiB (GPU 0; 23.70 GiB total capacity; 9.10 GiB already allocated; 12.91 GiB free; 9.10 GiB reserved in total by PyTorch) `

**Comment by Guillawme** [comment]
Do you know what other process is using the GPU (occupying the "already allocated" memory)? Can you stop it or wait until it completes to start your job?

**Comment by zhonge** [comment]
Sorry about the delay in responding. Hm, it is very strange that you are out of memory here. I suspect there was another process running on the GPU that was taking up most of the memory. Were you running on a cluster or potentially sharing the node with other users/programs?

**Comment by bu-bgregor** [comment]
I am working with @mttdoran on this. Cryodrgn is running on a GPU on a cluster but it had exclusive access to the GPU(s) so there wasn't any conflict with other software.

**Comment by 2subzero** [comment]
Here is the information. Please let me know if I can provide any thing else. 

Thank you for helping

Prash

Command:
`em/Cryodrgn/af4% cryodrgn train_vae particles.128.mrcs --poses poses.pkl --ctf ctf.pkl --zdim 8 -n 100 --enc-dim 256 --enc-layer 3 --dec-dim 256 --dec-layers 3 -b 1 --multigpu --lazy -o 00_vae128_256_100_z8`
Here is the output and error: `2022-03-24 15:52:48     /programs/x86_64-linux//cryodrgn/0.3.4_cu11/cryodrgn/bin/cryodrgn train_vae particles.128.mrcs --poses poses.pkl --ctf ctf.pkl --zdim 8 -n 100 --enc-dim 256 --enc-layer 3 --dec-dim 256 --dec-layers 3 -b 1 --multigpu --lazy -o 00_vae128_256_100_z8
2022-03-24 15:52:48     Namespace(activation='relu', amp=False, batch_size=1, beta=None, beta_control=None, checkpoint=1, ctf='/spot/em/Cryodrgn/af4/ctf.pkl', datadir=None, do_pose_sgd=False, domain='fourier', emb_type='quat', enc_mask=None, encode_mode='resid', func=<function main at 0x2aea22369ef0>, ind=None, invert_data=True, lazy=True, load=None, log_interval=1000, lr=0.0001, max_threads=16, multigpu=True, norm=None, num_epochs=100, outdir='/spot/em/Cryodrgn/af4/00_vae128_256_100_z8', particles='/spot/em/Cryodrgn/af4/particles.128.mrcs', pdim=256, pe_dim=None, pe_type='geom_lowf', players=3, pose_lr=0.0003, poses='/spot/em/Cryodrgn/af4/poses.pkl', preprocessed=False, pretrain=1, qdim=256, qlayers=3, relion31=False, seed=98468, tilt=None, tilt_deg=45, use_real=False, verbose=False, wd=0, window=True, window_r=0.85, zdim=8)
2022-03-24 15:52:48     Use cuda True
2022-03-24 15:52:48     Loading dataset from /spot/em/Cryodrgn/af4/particles.128.mrcs
2022-03-24 15:52:48     Loaded 96608 128x128 images
2022-03-24 15:52:50     Normalizing HT by 0 +/- 169.3788010515627
2022-03-24 15:53:23     Loading ctf params from /spot/em/Cryodrgn/af4/ctf.pkl
2022-03-24 15:53:23     Image size (pix)  : 128
2022-03-24 15:53:23     A/pix             : 1.6399999856948853
2022-03-24 15:53:23     DefocusU (A)      : 18722.16015625
2022-03-24 15:53:23     DefocusV (A)      : 18595.7578125
2022-03-24 15:53:23     Dfang (deg)       : 258.4698181152344
2022-03-24 15:53:23     voltage (kV)      : 300.0
2022-03-24 15:53:23     cs (mm)           : 2.700000047683716
2022-03-24 15:53:23     w                 : 0.10000000149011612
2022-03-24 15:53:23     Phase shift (deg) : 0.0
2022-03-24 15:53:23     Using circular lattice with radius 64
2022-03-24 15:53:24     HetOnlyVAE(
  (encoder): ResidLinearMLP(
    (main): Sequential(
      (0): Linear(in_features=12852, out_features=256, bias=True)
      (1): ReLU()
      (2): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (3): ReLU()
      (4): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (5): ReLU()
      (6): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (7): ReLU()
      (8): Linear(in_features=256, out_features=16, bias=True)
    )
  )
  (decoder): FTPositionalDecoder(
    (decoder): ResidLinearMLP(
      (main): Sequential(
        (0): Linear(in_features=392, out_features=256, bias=True)
        (1): ReLU()
        (2): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (3): ReLU()
        (4): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (5): ReLU()
        (6): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (7): ReLU()
        (8): Linear(in_features=256, out_features=2, bias=True)
      )
    )
  )
)
2022-03-24 15:53:24     3790354 parameters in model
2022-03-24 15:53:24     3491856 parameters in encoder
2022-03-24 15:53:24     298498 parameters in decoder
2022-03-24 15:53:24     Using 4 GPUs!
2022-03-24 15:53:24     Increasing batch size to 4
Traceback (most recent call last):
  File "/programs/x86_64-linux//cryodrgn/0.3.4_cu11/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.4', 'console_scripts', 'cryodrgn')())
  File "/programs/x86_64-linux/cryodrgn/0.3.4_cu11/cryodrgn_extlib/miniconda3-py37_4.10.3-e3qe/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/__main__.py", line 54, in main
    args.func(args)
  File "/programs/x86_64-linux/cryodrgn/0.3.4_cu11/cryodrgn_extlib/miniconda3-py37_4.10.3-e3qe/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/commands/train_vae.py", line 439, in main
    loss, gen_loss, kld = train_batch(model, lattice, y, yt, rot, tran, optim, beta, args.beta_control, tilt, ctf_params=ctf_param, yr=yr, use_amp=args.amp)
  File "/programs/x86_64-linux/cryodrgn/0.3.4_cu11/cryodrgn_extlib/miniconda3-py37_4.10.3-e3qe/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/commands/train_vae.py", line 100, in train_batch
    z_mu, z_logvar, z, y_recon, y_recon_tilt, mask = run_batch(model, lattice, y, yt, rot, tilt, ctf_params, yr)
  File "/programs/x86_64-linux/cryodrgn/0.3.4_cu11/cryodrgn_extlib/miniconda3-py37_4.10.3-e3qe/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/commands/train_vae.py", line 138, in run_batch
    z_mu, z_logvar = _unparallelize(model).encode(*input_)
  File "/programs/x86_64-linux/cryodrgn/0.3.4_cu11/cryodrgn_extlib/miniconda3-py37_4.10.3-e3qe/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/models.py", line 109, in encode
    z = self.encoder(*img)
  File "/programs/x86_64-linux/cryodrgn/0.3.4_cu11/cryodrgn_extlib/miniconda3-py37_4.10.3-e3qe/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7.egg/cryodrgn/models.py", line 108, in <genexpr>
    img = (x[:,self.enc_mask] for x in img)
RuntimeError: CUDA out of memory. Tried to allocate 18.14 GiB (GPU 0; 23.70 GiB total capacity; 9.10 GiB already allocated; 12.79 GiB free; 9.10 GiB reserved in total by PyTorch)`
Attached is the nvidia-smi screenshot

![image](https://user-images.githubusercontent.com/15055204/160009373-245ca661-c86f-4500-97c5-add0648db2e4.png)

**Comment by zhonge** [comment]
Hi, I'm going to close this issue -- the GPU memory utilization should not be that high, and it's challenging to debug remotely... There might be another process running on the machine that is using the GPU memory? One last suggestion would be to turn off `--multigpu`. There could be something going on with GPU parallelization causing the memory overload. Sorry, I can't be more helpful.
