### ISSUE TITLE
Issue with train_vae

### ISSUE THREAD

**Issue by mbelouso** [zhonge/cryodrgn#115]
When I run this command:

`cryodrgn train_vae data/particles_128box.mrcs --ctf data/ctf.pkl --poses data/poses.pkl --zdim 8 -n 8 --max-threads 4 -o process/00_vae_128 > vae_128.log`

I get the following error.

`2022-04-27 16:02:19     /home/cryosparc/anaconda3/envs/cryodrgn/bin/cryodrgn train_vae data/particles_128box.mrcs --ctf data/ctf.pkl --poses data/poses.pkl --zdim 8 -n 8 --max-threads 4 -o process/00_vae_128
2022-04-27 16:02:19     Namespace(activation='relu', amp=False, batch_size=8, beta=None, beta_control=None, checkpoint=1, ctf='/scratch/cryodrgn/mbelouso/GCGR_gluc/data/ctf.pkl', datadir=None, do_pose_sgd=False, domain='fourier', emb_type='quat', enc_mask=None, encode_mode='resid', feat_sigma=0.5, func=<function main at 0x7f878b856830>, ind=None, invert_data=True, lazy=False, load=None, log_interval=1000, lr=0.0001, max_threads=4, multigpu=False, norm=None, num_epochs=8, outdir='/scratch/cryodrgn/mbelouso/GCGR_gluc/process/00_vae_128', particles='/scratch/cryodrgn/mbelouso/GCGR_gluc/data/particles_128box.mrcs', pdim=256, pe_dim=None, pe_type='geom_lowf', players=3, pose_lr=0.0003, poses='/scratch/cryodrgn/mbelouso/GCGR_gluc/data/poses.pkl', preprocessed=False, pretrain=1, qdim=256, qlayers=3, seed=46876, tilt=None, tilt_deg=45, use_real=False, verbose=False, wd=0, window=True, window_r=0.85, zdim=8)
2022-04-27 16:02:19     Use cuda True
2022-04-27 16:02:19     Loading dataset from /scratch/cryodrgn/mbelouso/GCGR_gluc/data/particles_128box.mrcs
2022-04-27 16:03:31     Loaded 619686 128x128 images
2022-04-27 16:03:31     Windowing images with radius 0.85
2022-04-27 16:03:34     Computing FFT
2022-04-27 16:03:34     Spawning 4 processes
/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
  warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
Traceback (most recent call last):
  File "/home/cryosparc/anaconda3/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==1.0.0b0', 'console_scripts', 'cryodrgn')())
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-1.0.0b0-py3.7.egg/cryodrgn/__main__.py", line 58, in main
    args.func(args)
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-1.0.0b0-py3.7.egg/cryodrgn/commands/train_vae.py", line 330, in main
    data = dataset.MRCData(args.particles, norm=args.norm, invert_data=args.invert_data, ind=ind, keepreal=args.use_real, window=args.window, datadir=args.datadir, max_threads=args.max_threads, window_r=args.window_r, flog=flog)
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-1.0.0b0-py3.7.egg/cryodrgn/dataset.py", line 127, in __init__
    particles = np.asarray(p.map(fft.ht2_center, particles), dtype=np.float32)
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/cryosparc/anaconda3/envs/cryodrgn/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647`

It is with my own data, not the tutorial data. Please let me know if you need any more details.

Cheers

**Comment by zhonge** [comment]
Looks like an issue with multiprocessing (which can happen with large
datasets). Could you try --max-threads 1 ?
