### ISSUE TITLE
train_vae with --do-pose-sgd

### ISSUE THREAD

**Issue by jianhaoc** [zhonge/cryodrgn#122]
Hi, train_vae runs well without --do-pose-sgd. When I try to run train_vae with --do-pose-sgd, it doesn't work. The output (see below) says " Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!". I set up to limited the GPUs for cryodrgn running as the manual says. But it looks like I still miss something. 

$ export CUDA_VISIBLE_DEVICES=3
$ cryodrgn train_vae -o t001_box128_z8 --zdim 8 -n 50 --poses pose.pkl --ctf ctf.pkl --enc-dim 1024 --enc-layers 3 --dec-dim 1024 --dec-layers 3 --do-pose-sgd --domain hartley -v --amp data.mrcs

2022-07-06 14:38:50     /opt/conda3/envs/cryodrgn1/bin/cryodrgn train_vae -o t001_box128_z8 --zdim 8 -n 50 --poses pose.pkl --ctf ctf.pkl --enc-dim 1024 --enc-layers 3 --dec-dim 1024 --dec-layers 3 --do-pose-sgd --domain hartley -v --amp data.mrcs
2022-07-06 14:38:50     Namespace(particles='/ssd1/ntest/cryodrgn/data.mrcs', outdir='/ssd1/ntest/cryodrgn/t001_box128_z8', zdim=8, poses='/ssd1/ntest/cryodrgn/pose.pkl', ctf='/ssd1/ntest/cryodrgn/ctf.pkl', load=None, checkpoint=1, log_interval=1000, verbose=True, seed=44076, ind=None, invert_data=True, window=True, window_r=0.85, datadir=None, lazy=False, preprocessed=False, max_threads=16, tilt=None, tilt_deg=45, num_epochs=50, batch_size=8, wd=0, lr=0.0001, beta=None, beta_control=None, norm=None, amp=True, multigpu=False, do_pose_sgd=True, pretrain=1, emb_type='quat', pose_lr=0.0003, qlayers=3, qdim=1024, encode_mode='resid', enc_mask=None, use_real=False, players=3, pdim=1024, pe_type='geom_lowf', feat_sigma=0.5, pe_dim=None, domain='hartley', activation='relu', func=<function main at 0x7f30b63cd670>)
2022-07-06 14:38:50     Use cuda True
2022-07-06 14:38:50     Loading dataset from /ssd1/ntest/cryodrgn/data.mrcs
2022-07-06 14:38:59     Loaded 189953 128x128 images
2022-07-06 14:38:59     Windowing images with radius 0.85
2022-07-06 14:39:00     Computing FFT
2022-07-06 14:39:00     Spawning 16 processes
2022-07-06 14:41:07     Symmetrizing image data
2022-07-06 14:41:47     Normalized HT by 0 +/- 241.09457397460938
2022-07-06 14:41:51     Loading ctf params from /ssd1/ntest/cryodrgn/ctf.pkl
2022-07-06 14:41:51     Image size (pix)  : 128
2022-07-06 14:41:51     A/pix             : 2.1387999057769775
2022-07-06 14:41:51     DefocusU (A)      : 23211.416015625
2022-07-06 14:41:51     DefocusV (A)      : 22978.88671875
2022-07-06 14:41:51     Dfang (deg)       : -51.88908004760742
2022-07-06 14:41:51     voltage (kV)      : 300.0
2022-07-06 14:41:51     cs (mm)           : 2.700000047683716
2022-07-06 14:41:51     w                 : 0.10000000149011612
2022-07-06 14:41:51     Phase shift (deg) : 0.0
2022-07-06 14:41:51     Using circular lattice with radius 64
2022-07-06 14:41:51     HetOnlyVAE(
  (encoder): ResidLinearMLP(
    (main): Sequential(
      (0): Linear(in_features=12852, out_features=1024, bias=True)
      (1): ReLU()
      (2): ResidLinear(
        (linear): Linear(in_features=1024, out_features=1024, bias=True)
      )
      (3): ReLU()
      (4): ResidLinear(
        (linear): Linear(in_features=1024, out_features=1024, bias=True)
      )
      (5): ReLU()
      (6): ResidLinear(
        (linear): Linear(in_features=1024, out_features=1024, bias=True)
      )
      (7): ReLU()
      (8): Linear(in_features=1024, out_features=16, bias=True)
    )
  )
  (decoder): PositionalDecoder(
    (decoder): ResidLinearMLP(
      (main): Sequential(
        (0): Linear(in_features=392, out_features=1024, bias=True)
        (1): ReLU()
        (2): ResidLinear(
          (linear): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (3): ReLU()
        (4): ResidLinear(
          (linear): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (5): ReLU()
        (6): ResidLinear(
          (linear): Linear(in_features=1024, out_features=1024, bias=True)
        )
        (7): ReLU()
        (8): Linear(in_features=1024, out_features=1, bias=True)
      )
    )
  )
)
2022-07-06 14:41:51     19878929 parameters in model
2022-07-06 14:41:51     16326672 parameters in encoder
2022-07-06 14:41:51     3552257 parameters in deoder
2022-07-06 14:41:51     Warning: Masked input image dimension is not a mutiple of 8 -- AMP training speedup is not optimized
Traceback (most recent call last):
  File "/opt/conda3/envs/cryodrgn1/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==1.0.0b0', 'console_scripts', 'cryodrgn')())
  File "/opt/conda3/envs/cryodrgn1/lib/python3.9/site-packages/cryodrgn-1.0.0b0-py3.9.egg/cryodrgn/__main__.py", line 58, in main
    args.func(args)
  File "/opt/conda3/envs/cryodrgn1/lib/python3.9/site-packages/cryodrgn-1.0.0b0-py3.9.egg/cryodrgn/commands/train_vae.py", line 452, in main
    rot, tran = posetracker.get_pose(ind)
  File "/opt/conda3/envs/cryodrgn1/lib/python3.9/site-packages/cryodrgn-1.0.0b0-py3.9.egg/cryodrgn/pose.py", line 109, in get_pose
    rot = lie_tools.s2s2_to_SO3(self.rots_emb(ind))
  File "/opt/conda3/envs/cryodrgn1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda3/envs/cryodrgn1/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda3/envs/cryodrgn1/lib/python3.9/site-packages/torch/nn/functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

**Comment by dugu9sword** [comment]
It has been fixed in the latest commit.
