### ISSUE TITLE
cryodrgn analyze crash while running UMAP

### ISSUE THREAD

**Issue by lkater** [zhonge/cryodrgn#13]
Hi,
I ran the training on my own data (~900k particles, box size 130) like this and then tried to analyze some intermediate steps:

`cryodrgn train_vae stack130.mrcs --poses pose.pkl  --ctf ctf.pkl --zdim 10 -n 50 --qdim 1024 --qlayers 3 --pdim 1024 --players 3 -o 01_SE_z10_bx130 --lazy`

`cryodrgn analyze 01_SE_z10_bx130 18 --Apix 3.252 --device 1`

Whenever I do this I get a crash at the end of the analysis. I get volumes for PC1/2 and kmeans20 but I seem to be missing some pngs and the jupyter notebook files

Any Idea what could be causing this?

Log:

>2020-06-19 16:05:09     Saving results to /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18
2020-06-19 16:05:09     Perfoming principal component analysis...
2020-06-19 16:05:09     Explained variance ratio:
2020-06-19 16:05:09     [0.25000114 0.12236101 0.11018245 0.09589829 0.09308468 0.08158701
 0.07270409 0.06875768 0.05479458 0.05062907]
2020-06-19 16:05:09     K-means clustering...
2020-06-19 16:05:37     Generating volumes...
2020-06-19 16:05:37     Running command:
CUDA_VISIBLE_DEVICES=1 cryodrgn eval_vol /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl --config /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/config.pkl --zfile /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc1/z_values.txt -o /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc1 --Apix 3.252
2020-06-19 16:05:40     Use cuda True
2020-06-19 16:05:40     Namespace(Apix=3.252, D=130, config='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/config.pkl', domain='fourier', downsample=None, enc_mask=65, encode_mode='resid', flip=False, func=<function main at 0x7f0a9272b440>, l_extent=0.5, n=10, norm=[0, 130.7921984067214], o='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc1', pdim=1024, pe_dim=None, pe_type='geom_lowf', players=3, prefix='vol_', qdim=1024, qlayers=3, verbose=False, weights='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl', z=None, z_end=None, z_start=None, zdim=10, zfile='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc1/z_values.txt')
2020-06-19 16:05:42     Using circular lattice with radius 65
2020-06-19 16:05:42     Loading weights from /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl
2020-06-19 16:05:43     Generating 10 volumes
2020-06-19 16:05:43     [ 0.02677018  1.16648743 -1.00013293  0.37046741  0.03779986  1.58210712
 -0.21389392  0.75957619  0.09397226 -0.31373119]
2020-06-19 16:05:45     [-0.01569043  0.84260323 -0.71331644  0.2482569  -0.00333118  1.14377593
 -0.22116149  0.59137023  0.07997815 -0.26208557]
2020-06-19 16:05:48     [-0.05815104  0.51871902 -0.42649996  0.12604639 -0.04446223  0.70544475
 -0.22842907  0.42316426  0.06598405 -0.21043995]
2020-06-19 16:05:51     [-0.10061165  0.19483482 -0.13968347  0.00383587 -0.08559327  0.26711356
 -0.23569665  0.2549583   0.05198994 -0.15879433]
2020-06-19 16:05:53     [-0.14307226 -0.12904939  0.14713302 -0.11837464 -0.12672432 -0.17121763
 -0.24296423  0.08675234  0.03799583 -0.10714871]
2020-06-19 16:05:56     [-0.18553287 -0.45293359  0.4339495  -0.24058515 -0.16785536 -0.60954882
 -0.2502318  -0.08145363  0.02400173 -0.0555031 ]
2020-06-19 16:05:59     [-0.22799348 -0.7768178   0.72076599 -0.36279566 -0.20898641 -1.04788001
 -0.25749938 -0.24965959  0.01000762 -0.00385748]
2020-06-19 16:06:02     [-0.27045409 -1.10070201  1.00758247 -0.48500618 -0.25011745 -1.4862112
 -0.26476696 -0.41786556 -0.00398648  0.04778814]
2020-06-19 16:06:04     [-0.31291469 -1.42458621  1.29439896 -0.60721669 -0.2912485  -1.92454239
 -0.27203453 -0.58607152 -0.01798059  0.09943376]
2020-06-19 16:06:07     [-0.3553753  -1.74847042  1.58121545 -0.7294272  -0.33237955 -2.36287358
 -0.27930211 -0.75427748 -0.03197469  0.15107938]
2020-06-19 16:06:10     Finsihed in 0:00:31.376099
2020-06-19 16:06:11     Running command:
CUDA_VISIBLE_DEVICES=1 cryodrgn eval_vol /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl --config /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/config.pkl --zfile /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc2/z_values.txt -o /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc2 --Apix 3.252
2020-06-19 16:06:14     Use cuda True
2020-06-19 16:06:14     Namespace(Apix=3.252, D=130, config='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/config.pkl', domain='fourier', downsample=None, enc_mask=65, encode_mode='resid', flip=False, func=<function main at 0x7fc4e2df9440>, l_extent=0.5, n=10, norm=[0, 130.7921984067214], o='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc2', pdim=1024, pe_dim=None, pe_type='geom_lowf', players=3, prefix='vol_', qdim=1024, qlayers=3, verbose=False, weights='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl', z=None, z_end=None, z_start=None, zdim=10, zfile='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/pc2/z_values.txt')
2020-06-19 16:06:16     Using circular lattice with radius 65
2020-06-19 16:06:16     Loading weights from /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl
2020-06-19 16:06:16     Generating 10 volumes
2020-06-19 16:06:16     [ 1.26795325 -0.75064031 -0.33676747 -0.38691357  0.51339586  0.44470336
  0.67303123  0.36097304  0.62133282  0.43958098]
2020-06-19 16:06:19     [ 0.95961906 -0.56249652 -0.27260132 -0.30833687  0.37685765  0.37421879
  0.46977053  0.32547674  0.49331972  0.30971192]
2020-06-19 16:06:22     [ 0.65128487 -0.37435273 -0.20843517 -0.22976017  0.24031943  0.30373421
  0.26650983  0.28998044  0.36530663  0.17984287]
2020-06-19 16:06:25     [ 0.34295068 -0.18620894 -0.14426902 -0.15118348  0.10378121  0.23324964
  0.06324912  0.25448415  0.23729353  0.04997381]
2020-06-19 16:06:28     [ 0.03461649  0.00193485 -0.08010287 -0.07260678 -0.03275701  0.16276506
 -0.14001158  0.21898785  0.10928043 -0.07989524]
2020-06-19 16:06:30     [-0.2737177   0.19007864 -0.01593672  0.00596992 -0.16929522  0.09228049
 -0.34327229  0.18349156 -0.01873267 -0.2097643 ]
2020-06-19 16:06:33     [-0.58205189  0.37822243  0.04822943  0.08454661 -0.30583344  0.02179591
 -0.54653299  0.14799526 -0.14674576 -0.33963335]
2020-06-19 16:06:36     [-0.89038609  0.56636622  0.11239558  0.16312331 -0.44237166 -0.04868866
 -0.7497937   0.11249897 -0.27475886 -0.46950241]
2020-06-19 16:06:39     [-1.19872028  0.75451001  0.17656173  0.2417     -0.57890988 -0.11917324
 -0.9530544   0.07700267 -0.40277196 -0.59937146]
2020-06-19 16:06:41     [-1.50705447  0.9426538   0.24072788  0.3202767  -0.71544809 -0.18965781
 -1.1563151   0.04150638 -0.53078505 -0.72924052]
2020-06-19 16:06:44     Finsihed in 0:00:31.934163
2020-06-19 16:06:45     Running command:
CUDA_VISIBLE_DEVICES=1 cryodrgn eval_vol /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl --config /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/config.pkl --zfile /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/kmeans20/z_values.txt -o /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/kmeans20 --Apix 3.252
2020-06-19 16:06:48     Use cuda True
2020-06-19 16:06:48     Namespace(Apix=3.252, D=130, config='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/config.pkl', domain='fourier', downsample=None, enc_mask=65, encode_mode='resid', flip=False, func=<function main at 0x7fce93b994d0>, l_extent=0.5, n=10, norm=[0, 130.7921984067214], o='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/kmeans20', pdim=1024, pe_dim=None, pe_type='geom_lowf', players=3, prefix='vol_', qdim=1024, qlayers=3, verbose=False, weights='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl', z=None, z_end=None, z_start=None, zdim=10, zfile='/scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/analyze.18/kmeans20/z_values.txt')
2020-06-19 16:06:51     Using circular lattice with radius 65
2020-06-19 16:06:51     Loading weights from /scratch/lk/cryoDRGN_test2/01_SE_z10_bx130/weights.18.pkl
2020-06-19 16:06:51     Generating 20 volumes
2020-06-19 16:06:51     [-0.97132516 -0.64415139  1.90188849  0.34832573 -1.67768192 -2.35388446
 -0.97918421  0.40027481 -0.57715338  0.90271413]
2020-06-19 16:06:54     [-0.59527075  1.36312187 -0.56915736 -0.54813004 -0.82470226  0.73684198
 -0.01291508  0.48670399  0.92089242 -0.69209099]
2020-06-19 16:06:56     [-0.0711624   1.09866858 -1.84852767  0.22727478 -0.67786133  1.02027476
  0.78967232 -0.61266065  0.23449217  0.34753153]
2020-06-19 16:06:59     [-0.14201422 -1.40049565  1.12201524 -2.0198772  -0.76233393 -2.03652024
 -0.38700676 -0.23054661 -0.39152634 -0.43772185]
2020-06-19 16:07:02     [-0.16621244  0.81222612 -1.20070136 -0.31326452 -0.76325411  0.31952477
 -1.06328392  0.73861891 -0.71570486 -0.5696395 ]
2020-06-19 16:07:05     [-0.72862613  0.12580048 -0.75117576  1.07117748  0.57677025  1.36989951
 -0.00699391 -0.49410373 -1.05118728 -0.25212762]
2020-06-19 16:07:07     [-0.43604895 -1.51223695  0.66002649  0.35800946  0.45665389 -1.19505262
 -0.04969365 -2.26757884 -0.01168675  0.23415926]
2020-06-19 16:07:10     [-0.18047653  0.01970948  0.62216055  0.84891927  1.28573275  1.66495371
 -0.61027855  0.83711773  0.06010877 -0.74653506]
2020-06-19 16:07:13     [-0.1910335   0.34751123 -0.31187138  0.74085212  0.71890074  1.61903584
  0.31797802 -0.46175307  0.50515455 -0.30812699]
2020-06-19 16:07:16     [-1.60206747  0.92126781 -0.17496088  0.43709821 -0.3615002   1.04394341
 -0.79904234  0.60373396 -0.44559866 -0.7461015 ]
2020-06-19 16:07:19     [ 0.40465146  0.44999629  0.80674958  1.4138279  -1.33104229 -1.16981912
 -0.26164401  0.44663632  0.42494154  1.19738328]
2020-06-19 16:07:21     [ 0.59802741 -2.95357847  1.96336532 -0.59710884  0.59047776 -1.21152484
 -0.09131909 -0.28926587  0.17629631 -0.00756058]
2020-06-19 16:07:24     [ 0.77092814  0.35969877 -0.51961726 -0.52401483 -0.02129811  1.14776206
  0.40104675  1.6071167  -0.65990335  0.07273325]
2020-06-19 16:07:27     [ 0.08617193 -1.41762102 -0.02224282 -0.902996    0.02453905 -1.86269879
  0.67480099 -1.76085651 -0.01389218  1.05045223]
2020-06-19 16:07:30     [ 0.87995082 -0.17809655 -0.79066652  0.18712413  0.41063935  1.22204924
 -0.83809823  1.44176102  0.48284733 -0.23812459]
2020-06-19 16:07:33     [ 1.20228064  0.32292104 -1.41099977 -0.02424157  0.16307265  1.43185556
 -0.1174975  -0.32243931 -0.10479626  0.71535921]
2020-06-19 16:07:35     [ 0.77479064  0.13963751 -0.3947379   0.10177684  0.1000241   1.31804752
  0.50730151  1.11336291  1.3616066  -0.4266327 ]
2020-06-19 16:07:38     [-0.79391146  0.16412331  0.62868607 -0.64603126 -0.09520882 -1.21085966
  0.01015996  0.07755069  1.40696418 -0.88159704]
2020-06-19 16:07:41     [ 0.70707965  2.43540907  4.02419424  2.76443481 -1.47308397 -0.29974866
 -2.50558877 -2.63116574  1.03713751 -3.34746337]
2020-06-19 16:07:44     [-1.09395432 -1.4983263   0.95806909 -1.22308755  0.21075344 -1.88790619
 -1.16221488 -0.54821455 -0.60948658 -0.93069148]
2020-06-19 16:07:47     Finsihed in 0:00:59.782863
2020-06-19 16:07:47     Running UMAP...
Traceback (most recent call last):
  File "/home/lk/anaconda3/envs/cryodrgn/bin/cryodrgn", line 11, in <module>
    load_entry_point('cryodrgn==0.2.1b0', 'console_scripts', 'cryodrgn')()
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/__main__.py", line 50, in main
    args.func(args)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/commands/analyze.py", line 161, in main
    analyze_zN(z, outdir, vg, args.skip_umap)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/commands/analyze.py", line 88, in analyze_zN
    umap_emb = analysis.run_umap(z)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/analysis.py", line 68, in run_umap
    z_embedded = reducer.fit_transform(z)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/umap_learn-0.4.4-py3.7.egg/umap/umap_.py", line 2012, in fit_transform
    self.fit(X, y)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/umap_learn-0.4.4-py3.7.egg/umap/umap_.py", line 1833, in fit
    self._search_graph.transpose()
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/scipy-1.5.0rc1-py3.7-linux-x86_64.egg/scipy/sparse/lil.py", line 437, in transpose
    return self.tocsr(copy=copy).transpose(axes=axes, copy=False).tolil(copy=False)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/scipy-1.5.0rc1-py3.7-linux-x86_64.egg/scipy/sparse/lil.py", line 468, in tocsr
    _csparsetools.lil_get_lengths(self.rows, lengths)
  File "_csparsetools.pyx", line 109, in scipy.sparse._csparsetools.lil_get_lengths
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
TypeError: a bytes-like object is required, not 'list'

**Comment by zhonge** [comment]
Looks like it's crashing at UMAP, perhaps due to some memory issue. Can you try running UMAP separately and see what happens? 

> python $CDRGN_SRC/analysis_scripts/run_umap.py $WORKDIR/z.18.pkl -o $WORKDIR/analyze.18/umap.pkl

There are some resources here to help debug UMAP: https://umap-learn.readthedocs.io/en/latest/faq.html#i-ran-out-of-memory-help

You can get the rest of `cryodrgn analyze` to finish (and create the template jupyter notebook) with the argument `--skip-umap`. You can also use `--skip-vol` to skip volume generation since it's done that already.

**Comment by lkater** [comment]
I have run the command you suggested and tracked the memory usage on the system. It does not look like a memory issue. At most I get a peak at ~50% RAM (130GB) after which it goes down a little before crashing.  

>(959315, 10)
Traceback (most recent call last):
  File "/home/lk/cryodrgn/analysis_scripts/run_umap.py", line 39, in <module>
    main(parse_args().parse_args())
  File "/home/lk/cryodrgn/analysis_scripts/run_umap.py", line 30, in main
    z_embedded = reducer.fit_transform(z)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/umap_learn-0.4.4-py3.7.egg/umap/umap_.py", line 2012, in fit_transform
    self.fit(X, y)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/umap_learn-0.4.4-py3.7.egg/umap/umap_.py", line 1833, in fit
    self._search_graph.transpose()
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/scipy-1.5.0rc1-py3.7-linux-x86_64.egg/scipy/sparse/lil.py", line 437, in transpose
    return self.tocsr(copy=copy).transpose(axes=axes, copy=False).tolil(copy=False)
  File "/home/lk/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/scipy-1.5.0rc1-py3.7-linux-x86_64.egg/scipy/sparse/lil.py", line 468, in tocsr
    _csparsetools.lil_get_lengths(self.rows, lengths)
  File "_csparsetools.pyx", line 109, in scipy.sparse._csparsetools.lil_get_lengths
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
TypeError: a bytes-like object is required, not 'list'

**Comment by zhonge** [comment]
Hmm, I still suspect that it is a UMAP memory issue based on the traceback. Can you try running with `low_memory=True`? 


```
from cryodrgn import utils 
import umap
z = utils.load_pkl('path to z.pkl')
reducer = umap.UMAP()
z_embedded = reducer.fit_transform(z, low_memory=True)
```

You could also test if it works with a fraction of the dataset. Use the `--stride` option in the `run_umap.py` script.

**Comment by zhonge** [comment]
Closing this for now. Other options are to run GPU-enabled UMAP/tSNE (e.g. https://github.com/CannyLab/tsne-cuda) for computing the latent space embeddings.
