### ISSUE TITLE
len(ref_star) == len(particles) error in write_star.py

### ISSUE THREAD

**Issue by xyfzkd** [zhonge/cryodrgn#130]
A similar issue as in #101, if I divided my images into multiple groups by GMM or PCA clustering and wanted to build coordinates-kept .star files (imported to cryosparc and re-extracted for further processing) as:
`python ~/Softwares/cryodrgn/cryodrgn/commands_utils/write_star.py particles.128.txt ctf.pkl --poses pose.pkl --ind 00_cryodrgn128/ind_2.66091_particles.pkl -o class2_umap_GMM.star --ref-star ../2star.star  --keep-micrograph
`
(v1.0.0 or v1.1.0)
it didn't work...

filtering ref-star in issue #114 with 
```
python ~/Softwares/cryodrgn/cryodrgn/commands_utils/filter_star.py ../2star.star --ind 00_cryodrgn128/ind_2.66091_particles.pkl -o class2_umap_GMM_from2star.star

python ~/Softwares/cryodrgn/cryodrgn/commands_utils/write_star.py particles.128.txt ctf.pkl --poses pose.pkl --ind 00_cryodrgn128/ind_0.359404_particles.pkl -o test.star --ref-star class0_umap_GMM_from2star.star 

```
then I would encounter just the same error:

```
(cryodrgn) [zkyd@LFRZ_A1M2_301-01-10-05 P29]$ python ~/Softwares/cryodrgn/cryodrgn/commands_utils/write_star.py particles.128.txt ctf.pkl --poses pose.pkl --ind 00_cryodrgn128/ind_0.359404_particles.pkl -o test.star --ref-star class0_umap_GMM_from2star.star 
2022-08-21 04:52:01     673443 particles in particles.128.txt
Traceback (most recent call last):
  File "/home/zkyd/Softwares/cryodrgn/cryodrgn/commands_utils/write_star.py", line 148, in <module>
    main(args)
  File "/home/zkyd/Softwares/cryodrgn/cryodrgn/commands_utils/write_star.py", line 76, in main
    assert len(ref_star) == len(particles), f"{len(particles)} != {len(ref_star)}, Number of particles in {args.particles} != number of particles in {args.ref_star}"
AssertionError: 673443 != 359404, Number of particles in particles.128.txt != number of particles in class0_umap_GMM_from2star.star
```

last, I modified write_star.py by moving 
`assert len(ref_star) == len(particles), f"{len(particles)} != {len(ref_star)}, Number of particles in {args.particles} != number of particles in {args.ref_star}"`several lines below and it worked.
Here's the modified code
[write_star.py.zip](https://github.com/zhonge/cryodrgn/files/9388053/write_star.py.zip)

**Comment by vineetbansal** [comment]
@zhonge - using this thread to discuss the how `--ref-star` (and say `--ref-cs` if we were doing something similar for cryosparc files), is likely to be used by typical users, since it's related to the issue here:

If the intention of `--ref-star` is to supply additional metadata about particles, then the following assertion currently in our code, which happens *before* filtering by indices is done inside `write_star.py`
```
assert len(ref_star) == len(particles)
```
assumes that `--ref-star` should match the input `.mrcs` file exactly in terms of number of particles. This seems reasonable, and users like @xyfzkd here will know that's how its supposed to work if we made the error a bit more verbose.

@xyfzkd 's assumption is that `--ref-star` lookup happens *after* filtering by indices, in which case his fix is correct.

However, given that we're using `--ref-star` simply for adding columns to the resulting starfile, it seems to me somewhat restrictive that the above assertion should be in place at all, and users should be able to provide an unfiltered or filtered starfile, and "lining-up" should happen by matching up the `_rlnImageName` field in `--ref-star` and the `.mrc` file at the selected indices rather than implicitly by row numbers, as we're doing here:

https://github.com/zhonge/cryodrgn/blob/d29aea4ac7b31150fd6cde92cab1d43a7f7ede41/cryodrgn/commands_utils/write_star.py#L94

This will also take care of the case where a `--ref-star` is provided but `--ind` is not (and `--ref-star` and the input `.mrcs` don't exactly match up). This scenario will currently only write the first `|.mrc| - |ref-star|` rows, leaving the rest `na`.
 
 However, given that writing positional indices is so central to the `cryoDRGN` workflow, I might be overlooking something here that will make it too disruptive to implement.

**Comment by Guillawme** [comment]
I am also not sure if this would interfere with anything in cryoDRGN, but the behavior you describe with star file entries automatically "lined up" based on particle image name is the one that makes the most sense (that will cause the least amount of confusion, because the output would make sense), and that would work the same whether or not the initial set of particles was filtered at a later stage.
