### ISSUE TITLE
Support .cs file writing for export to cryoSPARC

### ISSUE THREAD

**Issue by zhonge** [zhonge/cryodrgn#150]
We should have a tool `cryodrgn_utils write_cs` to streamline re-importing particles to cryoSPARC.

If the input to cryoDRGN originated from cryoSPARC, this tool could keep certain (all?) fields like the `uid` from a reference .cs file. Then, the reimport to cryoSPARC wouldn't define an entirely new dataset.

I'm not 100% on what we would need to implement yet, but maybe we can refine the idea in this thread.

**Comment by zhonge** [comment]
Related to issues #72, #101, #148.

**Comment by zhonge** [comment]
One additional complexity is that particles are typically downsampled before training cryoDRGN, so the question is do we want the .cs file to point to the (new) downsampled particle stack or refer to the original extracted particles (more error-prone). 

In the latter case, the information that cryoDRGN provides is an index filtering. So maybe it makes sense to have a `cryodrgn_utils filter_cs` tool instead.

**Comment by Guillawme** [comment]
Being able to send a selection of particles back to cryoSPARC would be so useful!

And I think it is best as only a selection, pointing to the original particles in the cryoSPARC project (not re-importing the downsampled particles), because the typical use case is to refine a subset of particles to high resolution, using the particles at their original pixel size.

**Comment by Guillawme** [comment]
> Related to issues https://github.com/zhonge/cryodrgn/issues/72, https://github.com/zhonge/cryodrgn/issues/101, https://github.com/zhonge/cryodrgn/issues/148.

Also #109

**Comment by vineetbansal** [comment]
Just recapping some salient points from discussions with @zhonge about this:

  - The `write_star` command currently takes in a `.mrcs`/`.txt` file, a required ctf `.pkl`, an optional index `.pkl`, an optional poses `.pkl`
  - The command will be enhanced to take in a `.star` input in addition to `.mrcs`/`.txt`
  - If a `.star` is provided as input
    - All inputs other than an optional index `.pkl` will be ignored (and checked to make sure they are *not* specified).
    - All fields from the input `.star` will be carried over to the output `.star` file (including micrograph attributes, the original image name as _rlnImageName, ctf/pose information, anything else). Essentially the output `.star` will have exactly the same columns as in the input `.star`.
    - If an index `.pkl` is provided, the output `.star` will be filtered to have only those rows (row numbers are assumed 0-indexed). 
  - If a `.mrcs`/`.txt` file is provided as input, the behavior will remain unchanged.
 
A corresponding `write_cs` command will be implemented exactly as outlined above, except that it will take in either an input `.cs` file or an input `.mrcs`/`.txt` file. The command will mimic the behavior above, except that for `.cs` files.

A couple of additional points I'd like to propose here:

- The `cryodrgn filter_star` command will still be supported for existing users, though it will be refactored to internally use `write_star`. A `DeprecationWarning` will be emitted on its use and it may become unsupported at some future point (`write_star` can provide filtering as outlined above).
- A `cryodrgn filter_cs` command will *not* be implemented (`cryodrgn write_cs` can provide filtering as outlined above).

**Comment by Guillawme** [comment]
Seems like a great plan!

Sorry to bring this up again (https://github.com/zhonge/cryodrgn/pull/70#issuecomment-941061328), maybe you already discussed it and chose to not use an external library, but just in case you didn't: check out the [`starfile`](https://github.com/teamtomo/starfile) library, its goal is compatibility with star files from RELION, and it might simplify all your handling of star files (it turns star files into pandas dataframes and vice versa).

**Comment by vineetbansal** [comment]
Hi @Guillawme - I agree on using the `starfile` library. However, I'd like to handle that as a separate issue so the migration can be independent of anything we do here. I'll create an issue on that and hopefully we can get it done quickly.

**Comment by olibclarke** [comment]
I think this will also need to write a `.csg` file, right? In order to be able to import into Csparc using "Import Result Group"?

**Comment by zhonge** [comment]
Here's how to reimport a particle stack filtered by cryoDRGN back into cryoSPARC, while pointing to the original particles in the cryoSPARC project.

1. Export the original cryoSPARC particles from the associated Job so that there's a single `.cs` and `.csg` file describing the particle stack (i.e. no `PXXX_JYYY_passthrough_particles.cs` file). You can do this with the "Export" button in the Outputs tab.

![image](https://user-images.githubusercontent.com/5461028/224524914-c758687d-3234-4656-b7f5-6f74f86f57ce.png)


2. You'll find the `.cs` and `.csg` files in the `exports` subdirectory of your project directory: `/path/to/project/directory/PXXX/exports/groups/JYYY_particles`
 
3. Filter the .cs file with the index selection .pkl file using `cryodrgn_utils write_cs`. For example, here is the command to filter `J929_particles_exported.cs` by a selection saved in `ind_keep.214511_particles.pkl` and save out a new `J929_particles_filtered.cs` file:

```
(cryodrgn) $ cryodrgn_utils write_cs J929_particles_exported.cs --ind ind_keep.214511_particles.pkl -o J929_particles_filtered.cs
```

4. Make a copy of the `.csg` text file and replace the `metafile` field with the new .cs filename and the `num_items` field with the new number of particles. Here's a comparison of the before and after:

```
(cryodrgn) [Sat Mar 11 23:50 J929_particles] sdiff J929_particles_exported.csg J929_particles_filtered.csg
created: 2023-03-12 03:52:35.411011				created: 2023-03-12 03:52:35.411011
group:								group:
  description: All particles that were processed, including a	  description: All particles that were processed, including a
  name: particles						  name: particles
  title: All particles						  title: All particles
  type: particle						  type: particle
results:							results:
  alignments2D:							  alignments2D:
    metafile: '>J929_particles_exported.cs'		      |	    metafile: '>J929_particles_filtered.cs'
    num_items: 286801					      |	    num_items: 214511
    type: particle.alignments2D					    type: particle.alignments2D
  alignments3D:							  alignments3D:
    metafile: '>J929_particles_exported.cs'		      |	    metafile: '>J929_particles_filtered.cs'
    num_items: 286801					      |	    num_items: 214511
    type: particle.alignments3D					    type: particle.alignments3D
  blob:								  blob:
    metafile: '>J929_particles_exported.cs'		      |	    metafile: '>J929_particles_filtered.cs'
    num_items: 286801					      |	    num_items: 214511
    type: particle.blob						    type: particle.blob
  ctf:								  ctf:
    metafile: '>J929_particles_exported.cs'		      |	    metafile: '>J929_particles_filtered.cs'
    num_items: 286801					      |	    num_items: 214511
    type: particle.ctf						    type: particle.ctf
  location:							  location:
    metafile: '>J929_particles_exported.cs'		      |	    metafile: '>J929_particles_filtered.cs'
    num_items: 286801					      |	    num_items: 214511
    type: particle.location					    type: particle.location
  pick_stats:							  pick_stats:
    metafile: '>J929_particles_exported.cs'		      |	    metafile: '>J929_particles_filtered.cs'
    num_items: 286801					      |	    num_items: 214511
    type: particle.pick_stats					    type: particle.pick_stats
version: v4.1.2							version: v4.1.2
```

5. In cryoSPARC, use the "Import Results Group" job type and reimport the new `.csg` file. :tada: 

We can probably have `cryodrgn_utils write_cs` write out the `csg` file as well as @olibclarke suggested to skip over Step 4. It may be worth looking at the new `cryosparc-tools` API to see if there's a better way to write out the `.csg` file.

**Comment by Guillawme** [comment]
I just tried this and it seems it is going to work! :tada: 
(The file was generated, but I will know for sure when I'm able to copy these newly generated `.csg` and `.cs` files to the correct location; on our cluster we don't have write permission to the cryosparc project directory, but cryosparc will only import result groups from there, so I need somebody else to copy the files for me or change permissions.)

It would be great for usability if this tool could work this way (merging steps 3 and 4 above, as you say): 

- we point it to the _original_ `.csg` file (in the cryosparc exports directory) and the `ind.pkl` file (from the cryoDRGN job), and provide a file name for the `.csg` file to be newly created
- the tool then automatically
   + finds the original `.cs` file to filter (the one that the original `.csg` file points to)
   + saves the filtered `.cs` file in the current directory with the same base name as the newly created `.csg` file
   + makes a copy of the original `.csg` file to the file name provided
   + and finally edits this newly created `.csg` file to point to the filtered `.cs` file and contain the correct number of particles.

**Comment by cbeck22** [comment]
Hi @Guillawme, were you able to successfully import the particles into cryoSPARC? I've been having trouble because the `write_cs` command appears to output `.mrc` files instead of a `.cs` file.

After finding a cluster of 55963 particles in cryoDRGN (v3.3.3), I used this command to create the `.cs` file as described above. I had to use the `--datadir flag` to specify the cryoSPARC (v4.6) extraction job where the particle images originally came from. 
```
cryodrgn_utils write_cs /path-to-CS-project/exports/groups/J380_particles/J380_particles_exported.cs 
     --ind ind_GMM-2_cluster-0_55963-particles.pkl 
     -o /path-to-CS-project/exports/groups/J380_particles/J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs 
     --datadir /path-to-CS-project/J379/extract/
```

I also copied the `.csg` file and edited the names of the metafile and particle count, as described above:
```
created: 2024-09-23 21:07:31.234595
group:
  description: All particles that were processed, including alignments
  name: particles
  title: All particles
  type: particle
results:
  alignments2D:
    metafile: '>J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs'
    num_items: 55963
    type: particle.alignments2D
  alignments3D:
    metafile: '>J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs'
    num_items: 55963
    type: particle.alignments3D
  blob:
    metafile: '>J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs'
    num_items: 55963
    type: particle.blob
  ctf:
    metafile: '>J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs'
    num_items: 55963
    type: particle.ctf
  location:
    metafile: '>J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs'
    num_items: 55963
    type: particle.location
  pick_stats:
    metafile: '>J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs'
    num_items: 55963 
    type: particle.pick_stats
version: v4.6.0
```
However, when I tried importing this `.csg` file as a result group in cryoSPARC, I got this error:
```
 [CPU:  312.2 MB  Avail: 246.31 GB]

Importing result group from /path-to-CS-project/exports/groups/J380_particles/J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.csg
[CPU:  314.2 MB  Avail: 246.30 GB]

Traceback (most recent call last):
  File "/home/exx/cryosparc/cryosparc_worker/cryosparc_tools/cryosparc/dataset.py", line 615, in load
    return cls._load_numpy(file, prefixes=prefixes, fields=fields, cstrs=cstrs)
  File "/home/exx/cryosparc/cryosparc_worker/cryosparc_tools/cryosparc/dataset.py", line 654, in _load_numpy
    dset[field[0]][offset:end] = chunk[field[0]]
  File "/home/exx/cryosparc/cryosparc_worker/deps/anaconda/envs/cryosparc_worker_env/lib/python3.10/site-packages/numpy/core/memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cryosparc_master/cryosparc_compute/run.py", line 116, in cryosparc_master.cryosparc_compute.run.main
  File "/home/exx/cryosparc/cryosparc_worker/cryosparc_compute/jobs/imports/run.py", line 1337, in run_import_result_group
    output_group_dataset = dataset.Dataset.load(abs_cs_file_path)
  File "/home/exx/cryosparc/cryosparc_worker/cryosparc_tools/cryosparc/dataset.py", line 617, in load
    raise DatasetLoadError(f"Could not load dataset from file {file}") from err
cryosparc_tools.cryosparc.errors.DatasetLoadError: Could not load dataset from file /path-to-CS-project/exports/groups/J380_particles/J380_particles_exported_cryodrgn-filtered_GMM-2_cluster-0_55963-particles.cs
```
When I tried to examine the `.cs` file in a Jupyter notebook to see what was going wrong, I noticed that the dimensions of the numpy array encoded by the `.cs` file were (55963, 480, 480), which aren't the correct dimensions for a `.cs` file. Instead, it looks like the `.cs` file that `write_cs` generated are actually `.mrc files` of the 55963 particles with box size 480, which is the original box size of the particles:
```
print(cs.shape)
print(len(cs[0]))
print(len(cs[0][0]))
print(cs[0])

(55963, 480, 480)
480
480
[[-9.16041613e-01 -8.50794554e-01  1.13199872e-03 ... -5.62479973e-01
   2.04767182e-01 -1.01519811e+00]
 [ 6.54071808e-01 -1.12001944e+00  6.35961592e-02 ... -7.21155465e-01
   2.46697053e-01 -5.00065327e-01]
 [ 8.57174322e-02 -8.92888844e-01  2.81192213e-01 ... -9.65891123e-01
   1.09000027e+00  1.44568849e+00]
 ...
 [ 2.05566406e+00 -2.23506927e+00 -7.86724091e-01 ...  7.35788584e-01
   1.11828279e+00 -5.07942557e-01]
 [ 8.53600800e-01 -5.06177433e-02 -5.63970566e-01 ...  4.46593821e-01
   1.42825437e+00  1.20570585e-01]
 [ 1.59322107e+00 -8.58989775e-01 -1.37530005e+00 ...  8.22554111e-01
   3.34681198e-02  1.94161713e-01]]
```
I'm a little lost on why this happened, and I'd really appreciate any advice anyone can give.

Cheers,
cbeck

**Comment by Guillawme** [comment]
I haven't tried again since last year, but I can confirm that it worked back then when I followed [Ellen's directions above](https://github.com/ml-struct-bio/cryodrgn/issues/150#issuecomment-1465094751).

**Comment by michal-g** [comment]
I was able to reproduce this error using cryoDRGN v3.4.0, as well as v3.0.0 to make sure this wasn't due to any recent changes on our part. It seems that the latest versions of cryoSPARC are no longer compatible with the `numpy.array` format we are using in `write_cs`; I will try to include an update to this command in the upcoming cryoDRGN release!

**Comment by cbeck22** [comment]
Thank you Guillawme and Michal! For now, I was able to filter the `.cs` file by opening it as an array in a Jupyter notebook and indexing it using the list of indices in the `.pkl` file. 

Cheers,
cbeck

**Comment by michal-g** [comment]
As part of a pre-release of v3.4.1, I've made some preliminary updates to `write_cs`, which include making it do more or less what you have likely already implemented in your notebook for the case of filtering:
https://github.com/ml-struct-bio/cryodrgn/blob/3cc866e6cdf6c03eb3fd7265faab8c35808edc23/cryodrgn/commands_utils/write_cs.py#L50-L68

You can install this beta version using our beta release channel available through `pip`:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ 'cryodrgn<=3.4.1' --pre
```

If I recall correctly from another thread, you are using v3.3.3, so you may find some other new features available in [v3.4.0](https://github.com/ml-struct-bio/cryodrgn/releases/tag/3.4.0) (an already published stable release) to also be of interest! However, please remember that pre-releases are:
1) still subject to substantial changes (in this case, while not deprecating `write_cs`, we may reconsider introducing a `filter_cs` command for this particular use case as per the discussion above)
2) less thoroughly tested than full releases and more likely to have bugs

but also:

3) especially useful for garnering feedback and bug reports from users at an early stage of the development process

Let us know if you have problems with this installation or see any other issues with how the commands are running!

**Comment by cbeck22** [comment]
Would it be also possible to support modifying the .csg file? The approach that Ellen described above to manually edit the .csg file works, but gets a little tedious when exporting multiple groups of particles to cryoSPARC. As an example, I've copied my own implementation below:
```
def export_cs(particle_group, particle_indices, old_csfile, old_csgfile):
    # This function exports groups of particles from the dataframe created in cell 64 for PC/UMAP selection. It outputs
    #    a filtered .cs file and a modified .csg file
    # particle_group is the name of the group of particle indices
    # particle_indices is an array of indices
    # old_csfile is the path to the exported .csg file in exports/groups/ directory in the cryoSPARC project
    # old_csgfile is the path to the exported .csg file in exports/groups/ directory in the cryoSPARC project
        
    # Read the .cs file
    filtered_cs = np.load(old_csfile)
    print(f'Loaded {len(filtered_cs)} particles from {old_csfile}')
    
    # Filter the .cs file
    filtered_cs = filtered_cs[particle_indices]
    
    # Save the modified .cs file
    filtered_cs_filename = f'{particle_group}.{len(particle_indices)}.cs'
    cs_SAVE_PATH = f'{WORKDIR}/analyze.{EPOCH}/pc1/{filtered_cs_filename}'
    #print(len(filtered_cs))
    #print(cs_SAVE_PATH)
    np.save(cs_SAVE_PATH, filtered_cs)
    os.rename(f'{cs_SAVE_PATH}.npy', cs_SAVE_PATH)
    print(f'Saved {len(particle_indices)} particles to {cs_SAVE_PATH}')
    
    # Read the .csg file
    with open(old_csgfile, 'r') as file:
        csg_data = yaml.safe_load(file)
        
    # Modify the .csg file
    for result_key, result_data in csg_data['results'].items():
        result_data['metafile'] = filtered_cs_filename  # Update metafile
        result_data['num_items'] = len(particle_indices)  # Update num_items
        
    # Write the modified data to a new .csg file
    new_csg_filename = f'{filtered_cs_filename}g'
    csg_SAVE_PATH = f'{WORKDIR}/analyze.{EPOCH}/pc1/{new_csg_filename}'
    print(f'.csg file saved to {csg_SAVE_PATH}')
    
    with open(csg_SAVE_PATH, 'w') as file:
        yaml.dump(csg_data, file, default_flow_style=False)
```
