### ISSUE TITLE
Error running abinit_het

### ISSUE THREAD

**Issue by olibclarke** [zhonge/cryodrgn#166]
Hi,

When I run `abinit_het` on a small 20k subset of EMPIAR-11043 using version `1.0.1.dev126+g04c4a90`, it fails with the attached error. `abinit_homo` runs without a problem using the same inputs.

This is the command I used:
`cryodrgn abinit_het ank_downsample_128.mrcs --ind round1_keep.pkl --ctf ank_ctf.pkl -n 60 --zdim 8 -o abinit_het_test/ >> abinit_het_test.log`

And here is the end of the log:
```
2022-10-25 08:52:09     3790354 parameters in model
2022-10-25 08:52:09     Using random poses for 10000 iterations
Traceback (most recent call last):
  File "/usr/local/envs/cryodrgn2/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/envs/cryodrgn2/lib/python3.9/site-packages/cryodrgn/__main__.py", line 64, in main
    args.func(args)
  File "/usr/local/envs/cryodrgn2/lib/python3.9/site-packages/cryodrgn/commands/abinit_het.py", line 507, in main
    loss = pretrain(model, lattice, optim, batch, tilt=ps.tilt)
  File "/usr/local/envs/cryodrgn2/lib/python3.9/site-packages/cryodrgn/commands/abinit_het.py", line 143, in pretrain
    z = torch.randn((B,args.zdim), device=y.device)
NameError: name 'args' is not defined
```

**Comment by vineetbansal** [comment]
Thanks @olibclarke - the fix for this bug is in the queue and should be available in the `master` branch shortly.

**Comment by vineetbansal** [comment]
@olibclarke - this bug has been fixed in the `master` branch. I'm closing this issue, but feel free to open in case we've overlooked anything here.
