### ISSUE TITLE
analyze_landscape_full pytorch cuda problem

### ISSUE THREAD

**Issue by papaig** [zhonge/cryodrgn#179]
Hi,

I completed the analyze_landscape command without any issues. Then I tried to create the free energy landscape with the analyze_landscape_full command. It finished the 10000 volume embeddings but after that it crashed with this error message:
File "/home/papai/.conda/envs/cryodrgn1.1/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/__main__.py", line 64, in main
    args.func(args)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/commands/analyze_landscape_full.py", line 244, in main
    embeddings_all = train_model(z, embeddings, outdir, zfile, args)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/commands/analyze_landscape_full.py", line 194, in train_model
    train(args, model, device, train_loader, optimizer, epoch)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/commands/analyze_landscape_full.py", line 63, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1072, in __init__
    self._reset(loader, first_iter=True)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1105, in _reset
    self._try_put_index()
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1339, in _try_put_index
    index = self._next_index()
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 618, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 132, in __iter__
    yield from torch.randperm(n, generator=generator).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

I followed this advice to change the torch/utils/data/sampler.py file:  https://stackoverflow.com/a/71780879

I rerun and got the following error after the volume embeddings:
File "/home/papai/.conda/envs/cryodrgn1.1/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/__main__.py", line 64, in main
    args.func(args)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/commands/analyze_landscape_full.py", line 244, in main
    embeddings_all = train_model(z, embeddings, outdir, zfile, args)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/commands/analyze_landscape_full.py", line 194, in train_model
    train(args, model, device, train_loader, optimizer, epoch)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/cryodrgn/commands/analyze_landscape_full.py", line 63, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 172, in <listcomp>
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/papai/.conda/envs/cryodrgn1.1/lib/python3.9/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

Then I reverted the torch/utils/data/sampler.py file to its original content and tried this advice: https://stackoverflow.com/a/68621335

After this change I received the same error as for the first trial.

I installed pytorch with: conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia

I would appreciate your help!

Best regards,
Gabor

**Comment by junsun-commits** [comment]
Hi all,
Sorry to bring this up back. Is this issue solved in the recent version of cryodrgn?
I also get the same issue for analyze_ladnscape_full when using ver 2.3.0.
Is pytorch version or compatibility making this issue?

Best,
Junsun
