### ISSUE TITLE
amp running error

### ISSUE THREAD

**Issue by kimdn** [zhonge/cryodrgn#20]
I uninstalled cryodrgn and reinstalled.

Then, according to
`https://github.com/NVIDIA/apex#quick-start`
I re-installed Apex via Python-only build (because installation via CUDA and C++ extensions errored).

However,

`~/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/bin/cryodrgn train_vae cryosparc_P4_J251_009_particles_cs_abs_w_mrcs_star_06_25.64.mrcs --poses pose_128.pkl --ctf ctf.pkl --zdim 64 -n 100 -o vae64_z64_e100_b_64_amp_wo_tonga_interactive --batch-size 64 --amp`

resulted in

`2020-09-07 19:19:31     1315458 parameters in model
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.
Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Traceback (most recent call last):
  File "/people/kimd999/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.2.1b0', 'console_scripts', 'cryodrgn')())
  File "/people/kimd999/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/__main__.py", line 50, in main
    args.func(args)
  File "/people/kimd999/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/commands/train_vae.py", line 364, in main
    model, optim = amp.initialize(model, optim, opt_level='O1')
  File "/people/kimd999/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/lib/python3.7/site-packages/apex/amp/frontend.py", line 358, in initialize
    return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
  File "/people/kimd999/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/lib/python3.7/site-packages/apex/amp/_initialize.py", line 171, in _initialize
    check_params_fp32(models)
  File "/people/kimd999/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/lib/python3.7/site-packages/apex/amp/_initialize.py", line 93, in check_params_fp32
    name, param.type()))
  File "/people/kimd999/bin/Miniconda3-latest-Linux-x86_64/envs/cryodrgn/lib/python3.7/site-packages/apex/amp/_amp_state.py", line 32, in warn_or_err
    raise RuntimeError(msg)
RuntimeError: Found param encoder.main.0.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.`

**Comment by zhonge** [comment]
For some reason, the GPU is no longer recognized, either from your reinstall or the additional installation of apex.

You can test the cryodrgn install by the following script from the cryodrgn repo:

> $ cd [cryodrgn repo]/testing
> $ ./quicktest.sh

It should finish in ~10s. Look for `Use cuda True` at the top of the logged output to check that it ran on the GPUs.

**Comment by kimdn** [comment]
It is 
`Use cuda False`
I missed to recognized this change.

I will re-install.

**Comment by apayne97** [comment]
I got maybe a similar error? 

```
(cryodrgn) paynea@ls05:/data/hite/GPCR/cryodrgn-LPAR/cryodrgn-vae-z8-50epochs$ cryodrgn train_vae /data/hite/GPCR/cryodrgn-LPAR/particle-stacks/particles.128.mrcs --poses /data/hite/GPCR/cryodrgn-LPAR/pickles/pose.pkl --ctf /data/hite/GPCR/cryodrgn-LPAR/pickles/ctf.pkl --invert-data --amp -b 16 --zdim 8 -n 50 -o 00-vae-z8 --lazy
2020-09-11 14:49:26     /home/paynea/miniconda3/envs/cryodrgn/bin/cryodrgn train_vae /data/hite/GPCR/cryodrgn-LPAR/particle-stacks/particles.128.mrcs --poses /data/hite/GPCR/cryodrgn-LPAR/pickles/pose.pkl --ctf /data/hite/GPCR/cryodrgn-LPAR/pickles/ctf.pkl --invert-data --amp -b 16 --zdim 8 -n 50 -o 00-vae-z8 --lazy
2020-09-11 14:49:26     Namespace(amp=True, batch_size=16, beta=1.0, beta_control=None, checkpoint=1, ctf='/data/hite/GPCR/cryodrgn-LPAR/pickles/ctf.pkl', datadir=None, do_pose_sgd=False, domain='fourier', emb_type='quat', enc_mask=None, encode_mode='resid', func=<function main at 0x2b56884df830>, ind=None, invert_data=True, lazy=True, load=None, log_interval=1000, lr=0.0001, norm=None, num_epochs=50, outdir='/lila/data/hite/GPCR/cryodrgn-LPAR/cryodrgn-vae-z8-50epochs/00-vae-z8', particles='/data/hite/GPCR/cryodrgn-LPAR/particle-stacks/particles.128.mrcs', pdim=256, pe_dim=None, pe_type='geom_lowf', players=3, pose_lr=0.0003, poses='/data/hite/GPCR/cryodrgn-LPAR/pickles/pose.pkl', pretrain=1, qdim=256, qlayers=3, relion31=False, seed=63367, tilt=None, tilt_deg=45, use_real=False, verbose=False, wd=0, window=False, zdim=8)
2020-09-11 14:49:26     Use cuda True
2020-09-11 14:49:28     Loaded 500000 128x128 images
2020-09-11 14:50:46     Normalizing HT by 0 +/- 308.34689291371905
2020-09-11 14:50:54     Loading ctf params from /data/hite/GPCR/cryodrgn-LPAR/pickles/ctf.pkl
2020-09-11 14:50:54     Image size (pix)  : 128
2020-09-11 14:50:54     A/pix             : 2.128000020980835
2020-09-11 14:50:54     DefocusU (A)      : 27189.162109375
2020-09-11 14:50:54     DefocusV (A)      : 26174.470703125
2020-09-11 14:50:54     Dfang (deg)       : 44.87660217285156
2020-09-11 14:50:54     voltage (kV)      : 300.0
2020-09-11 14:50:54     cs (mm)           : 3.343641757965088
2020-09-11 14:50:54     w                 : 0.10000000149011612
2020-09-11 14:50:54     Phase shift (deg) : -4.3616108894348145
2020-09-11 14:50:54     Using circular lattice with radius 64
2020-09-11 14:50:54     HetOnlyVAE(
  (encoder): ResidLinearMLP(
    (main): Sequential(
      (0): Linear(in_features=12852, out_features=256, bias=True)
      (1): ReLU()
      (2): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (3): ReLU()
      (4): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (5): ReLU()
      (6): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (7): ReLU()
      (8): Linear(in_features=256, out_features=16, bias=True)
    )
  )
  (decoder): FTPositionalDecoder(
    (decoder): ResidLinearMLP(
      (main): Sequential(
        (0): Linear(in_features=392, out_features=256, bias=True)
        (1): ReLU()
        (2): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (3): ReLU()
        (4): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (5): ReLU()
        (6): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (7): ReLU()
        (8): Linear(in_features=256, out_features=2, bias=True)
      )
    )
  )
)
2020-09-11 14:50:54     3790354 parameters in model
2020-09-11 14:50:54     Warning: Masked input image dimension is not a mutiple of 8 -- AMP training speedup is not optimized
Traceback (most recent call last):
  File "/home/paynea/miniconda3/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.2.1b0', 'console_scripts', 'cryodrgn')())
  File "/home/paynea/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/__main__.py", line 50, in main
    args.func(args)
  File "/home/paynea/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/commands/train_vae.py", line 364, in main
    model, optim = amp.initialize(model, optim, opt_level='O1')
NameError: name 'amp' is not defined
```

**Comment by apayne97** [comment]
command is here:
```
cryodrgn train_vae /data/hite/GPCR/cryodrgn-LPAR/particle-stacks/particles.128.mrcs --poses /data/hite/GPCR/cryodrgn-LPAR/pickles/pose.pkl --ctf /data/hite/GPCR/cryodrgn-LPAR/pickles/ctf.pkl --invert-data --amp -b 16 --zdim 8 -n 50 -o 00-vae-z8 --lazy
```

**Comment by kimdn** [comment]
> It is `Use cuda False`
> I missed to recognize this change.
> 
> I will re-install.

It turns out that I didn't add 
`-c pytorch`
to 
` conda install pytorch cudatoolkit=9.2 `

Once I added it when I reinstalled both cryodrgn and amp, amp is detected.

Just now I encounter some dimension that is not optimized for amp usage.

**Comment by zhonge** [comment]
@apayne97 you may need to check that amp was installed correctly into your conda environment. I was able to `conda install apex` in my environment. There is also the guide found here (https://github.com/NVIDIA/apex#quick-start).

@kimdn For 128x128 images, you would need to set `--enc-mask 61` to get the input dimension to be an even multiple of 8. I don't usually bother with modifying `--enc-mask` since I don't notice too big of a performance difference on 128 images. Usually the biggest performance gains using amp is with larger images or larger architectures. For 256 images, the input mask happens to be a multiple of 8 by default :).
