### ISSUE TITLE
analyze error message

### ISSUE THREAD

**Issue by kimdn** [zhonge/cryodrgn#22]
Command was
`cryodrgn analyze vae128_z10_e100_conv 75 --Apix 0.2966015625 --ksample 3`

```
...
2020-09-19 22:52:56     Generating 3 volumes
2020-09-19 22:52:56     [ 8.76704752e-02 -3.42603713e-01  1.30035257e+00  1.18819630e+00
  1.42611980e-01 -1.22894645e-02 -1.77807882e-01  4.19831753e-01
  5.52097082e-01  7.15658069e-04]
2020-09-19 22:53:02     [-0.60905266  0.1405278   0.11575085 -1.17220247  0.0083428   0.01721188
  0.06637335  0.77177167  0.17333728 -0.13592422]
2020-09-19 22:53:08     [ 0.72590917  0.10197172 -0.96716791 -0.3785781  -0.0888432  -0.39900404
  0.07986095 -0.39363769  0.14182752 -0.13963668]
2020-09-19 22:53:12     Finsihed in 0:00:20.618744
2020-09-19 22:53:17     Running UMAP...
2020-09-19 22:58:51     Generating plots...
2020-09-19 22:59:11     Creating jupyter notebook...
/bin/sh: 1: cp: not found
Traceback (most recent call last):
  File "/people/kimd999/.conda/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.2.1b0', 'console_scripts', 'cryodrgn')())
  File "/people/kimd999/.conda/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/__main__.py", line 50, in main
    args.func(args)
  File "/people/kimd999/.conda/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/commands/analyze.py", line 168, in main
    subprocess.check_call(cmd, shell=True)
  File "/people/kimd999/.conda/envs/cryodrgn/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp /people/kimd999/.conda/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/templates/cryoDRGN_viz_template.ipynb /pic/projects/MARScryo/dn/cryodrgn/exp/PDX/coexp/latest/vae128_z10_e100_conv/analyze.75/cryoDRGN_viz.ipynb' returned non-zero exit status 127.
```

Since I use cp command all the time in my linux terminal tab (who wouldn't?), I don't understand why it says 
`/bin/sh: 1: cp: not found`

This cp command appears to do nothing but just copying template notebook file as in
`cp /people/kimd999/.conda/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.2.1b0-py3.7.egg/cryodrgn/templates/cryoDRGN_viz_template.ipynb /pic/projects/MARScryo/dn/cryodrgn/exp/PDX/coexp/latest/vae128_z10_e100_conv/analyze.75/cryoDRGN_viz.ipynb`

Therefore, for now, I can just copy template notebook file manually, but it will be nice if it is done automatically.

**Comment by kimdn** [comment]
Once I re-installed a newer version, the error is gone. Close now.
