### ISSUE TITLE
TypeError on model eval after `cryodrgn abinit_het`

### ISSUE THREAD

**Issue by zhonge** [zhonge/cryodrgn#223]
`cryodrgn analyze` fails on a model trained with `cryodrgn abinit_het`. I'm not sure when this happened, but we should fix this bug, and then add a unit test for this.

(INFO) (eval_vol.py) (12-Feb-23 11:09:36) [ 1.34725974 -0.42654238  2.27259662  1.65876899 -2.16554683 -3.53140053
 -1.72760322  1.96388295]
Traceback (most recent call last):
  File "/home/zhonge/.conda/envs/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/zhonge/dev/cryodrgn/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/zhonge/dev/cryodrgn/cryodrgn/commands/analyze.py", line 255, in main
    analyze_zN(
  File "/home/zhonge/dev/cryodrgn/cryodrgn/commands/analyze.py", line 112, in analyze_zN
    vg.gen_volumes(f"{outdir}/pc{i+1}", z_pc)
  File "/home/zhonge/dev/cryodrgn/cryodrgn/commands/analyze.py", line 217, in gen_volumes
    analysis.gen_volumes(self.weights, self.config, zfile, outdir, **self.vol_args)
  File "/home/zhonge/dev/cryodrgn/cryodrgn/analysis.py", line 581, in gen_volumes
    return eval_vol.main(args)
  File "/home/zhonge/dev/cryodrgn/cryodrgn/commands/eval_vol.py", line 204, in main
    vol = model.decoder.eval_volume(
  File "/home/zhonge/dev/cryodrgn/cryodrgn/models.py", line 384, in eval_volume
    x = torch.cat((x, zval), dim=-1)
TypeError: expected Tensor as element 1 in argument 0, but got numpy.ndarray

**Comment by zhonge** [comment]
The type error was in `PositionalDecoder.eval_volume` where we were trying to concatenate a np array with torch tensor. We don't typically hit this in standard cryoDRGN(1) since the default model class is `FTPositionalDecoder`. Two notes:
* We might not have hit this earlier in an older version of pytorch... but we should definitely add a regression test for running cryodrgn analyze after cryodrgn abinit_het.
* We could refactor `PositionalDecoder` and `FTPositionalDecoder` to avoid code reuse in `eval_volume`.
