### ISSUE TITLE
Another type error in cryodrgn analyze

### ISSUE THREAD

**Issue by xiazeqing** [zhonge/cryodrgn#238]
**Describe the bug**
`Traceback (most recent call last):
  File "/opt/conda/envs/cryodrgn/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/cryodrgn/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/conda/envs/cryodrgn/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/envs/cryodrgn/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/envs/cryodrgn/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/users/xiazeqing/cryodrgn/testing/our_anal_sim20k_abinit.py", line 20, in <module>
    cryodrgn.analysis.gen_volumes(weights=os.path.join(rootdir,'weights.pkl'),config=os.path.join(rootdir,'config.pkl'),zfile=os.path.join(rootdir,'za.txt'),outdir=os.path.join(rootdir,'our_anal_median'))
  File "/opt/conda/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/analysis.py", line 577, in gen_volumes
    return eval_vol.main(args)
  File "/opt/conda/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands/eval_vol.py", line 205, in main
    vol = model.decoder.eval_volume(
  File "/opt/conda/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/models.py", line 385, in eval_volume
    x = torch.cat((x, zval), dim=-1)
TypeError: expected Tensor as element 1 in argument 0, but got numpy.ndarray`

**To Reproduce**
What is the command you used?
`
import cryodrgn.analysis
cryodrgn.analysis.gen_volumes(weights=os.path.join(rootdir,'weights.pkl'),config=os.path.join(rootdir,'config.pkl'),zfile=os.path.join(rootdir,'za.txt'),outdir=os.path.join(rootdir,'our_anal_median'))`

**Expected behavior**
In `/opt/conda/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/models.py` Line 352:
`
def eval_volume(
        self,
        coords: Tensor,
        D: int,
        extent: float,
        norm: Norm,
        zval: Optional[np.ndarray] = None,
    ) -> np.ndarray:
        """
        Evaluate the model on a DxDxD volume

        Inputs:
            coords: lattice coords on the x-y plane (D^2 x 3)
            D: size of lattice
            extent: extent of lattice [-extent, extent]
            norm: data normalization
            zval: value of latent (zdim x 1)
        """
        # Note: extent should be 0.5 by default, except when a downsampled
        # volume is generated
        if zval is not None:
            zdim = len(zval)
            z = torch.zeros(D**2, zdim, dtype=torch.float32, device=coords.device)
            z += torch.tensor(zval, dtype=torch.float32, device=coords.device)

        vol_f = np.zeros((D, D, D), dtype=np.float32)
        assert not self.training
        # evaluate the volume by zslice to avoid memory overflows
        for i, dz in enumerate(
            np.linspace(-extent, extent, D, endpoint=True, dtype=np.float32)
        ):
            x = coords + torch.tensor([0, 0, dz], device=coords.device)
            if zval is not None:
                x = torch.cat((x, zval), dim=-1)
            with torch.no_grad():
                y = self.forward(x)
                y = y.view(D, D).cpu().numpy()
            vol_f[i] = y
        vol_f = vol_f * norm[1] + norm[0]
        vol = fft.ihtn_center(
            vol_f[0:-1, 0:-1, 0:-1]
        )  # remove last +k freq for inverse FFT
        return vol
`
zval is inputed as a ndarray, but Line 385 directly added x(torch.Tensor) and zval(np.ndarray).

Line 384 and 385 should be "z" instead of "zval"?

**Comment by xiazeqing** [comment]
Ah, that's an issue in 2.0.0. Already fixed in 2.1.0.
