### ISSUE TITLE
Get "ImportError: attempted relative import with no known parent package" when run test_mrc.py on Windows

### ISSUE THREAD

**Issue by Icecream-blue-sky** [zhonge/cryodrgn#28]
When I run test_mrc.py, I  get the error below:
```python
Traceback (most recent call last):
  File "D:/Study/The Road to AI/AIRoad/cryodrgn/testing/test_mrc.py", line 13, in <module>
    import dataset
  File "D:\Study\The Road to AI\AIRoad\cryodrgn\testing/../cryodrgn\dataset.py", line 7, in <module>
    from . import fft
ImportError: attempted relative import with no known parent package
```
It's cause by the code of cryodrgn/dataset.py:
```python
from . import fft
from . import mrc
from . import utils
from . import starfile
```
I want to konw how to fix it? And dose it only appear on Windows? 
My computer system is Win10, and I run the code on PyCharm.

**Comment by zhonge** [comment]
Fixed in 879b4227e9e714c3b0f153026f80f03d7c7131e9. Thanks!
