### ISSUE TITLE
Only a single particle stack supported for write_starfile.py

### ISSUE THREAD

**Issue by rubyfroom** [zhonge/cryodrgn#44]
After selecting particles using the Jupyter notebook, I am unable to convert them to a .star file. My input:

```
python $SRC/utils/write_starfile.py particles.256.txt ctf.pkl --ind ind_keep.6795_particles.pkl -o output.star
```

Output:

```
Traceback (most recent call last):
  File "/home/darst/cryodrgn/utils/write_starfile.py", line 91, in <module>
    main(parse_args().parse_args())
  File "/home/darst/cryodrgn/utils/write_starfile.py", line 44, in main
    assert args.particles.endswith('.mrcs'), "Only a single particle stack as an .mrcs is currently supported"
AssertionError: Only a single particle stack as an .mrcs is currently supported
```

Thank you!

**Comment by zhonge** [comment]
Added in commit 171c86c8befcddc4f43a40f4be464a80b6713a1a. Let me know if there are any issues!

**Comment by rubyfroom** [comment]
Thanks Ellen! The following lines of code caused `SyntaxError: invalid syntax`, which could be fixed by deleting the `f` that was in front of some of the arguments:

```  File "/path/to/cryodrgn/utils/write_starfile.py", line 49
    assert len(particles) == len(ctf), f"{len(particles)} != {len(ctf)}, Number of particles != number of CTF paraameters"```

```    File "/path/to/cryodrgn/utils/write_starfile.py", line 52
    assert len(particles) == len(poses[0]), f"{len(particles)} != {len(poses)}, Number of particles != number of poses"```

```  File "/home/darst/cryodrgn/utils/write_starfile.py", line 57
    log(f'Filtering to {len(ind)} particles')```

```  File "/home/darst/cryodrgn/utils/write_starfile.py", line 69
    names = [f'{i}@{name}' for i,name in zip(ind, image_names)]```
