### ISSUE TITLE
write_starfile.py giving corrupt .star files

### ISSUE THREAD

**Issue by ArmandoPach** [zhonge/cryodrgn#62]
Hi,

Whenever I try to generate a .star file with filtered particles I only get a corrupt file that weights tops ~10 megabytes. 

I tried using .star, .mrcs and .cs files as inputs but I always get the same result.

I have also tried filtering my particles using the .mrcs stack (that I know has particles because I generated a png out of it and also weights some gigabytes) then transforming it to a .star but the same thing happenes.

For everything I've been using the same ctf.pkl and poses.pkl that I am using for training and so far the training is going well and is yielding good results, so I don't think these files are bad/corrupt.

I also tried grabbing the filtered .mrcs stack and using pyem's stack.py to transform it to a .star but for whatever reason it failes due to a decoding error.

I am by no means a python script expert so don't shrug off the idea of me doing something bad, but I wanted to post it here given that I've tried to troubleshoot it myself for some days now and I don't think I am getting anywhere.

All the best,
Armando

**Comment by zhonge** [comment]
Hi Armando! Can you provide the full command you used?

**Comment by ArmandoPach** [comment]
Hi Ellen!

Thanks for the quick response.

Here's the full command I used:

python write_starfile.py /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/96Px/P16_J1536_particles/P16_J1536_particles_exported.cs /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/ctf.pkl --ind /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Trainings/HD_96_vae_01/Class1_Epoch_055.pkl --datadir /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/96Px/P16_J1536_particles/J1536/downsample/ --full-path -o /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/Class1_Epoch_055_96_Px.star

My particles come from an exported cryoSPARC job and they are the exact same particles I used for my training job.

Also, whenever I try to use the "--poses" argument I get the following error:

Traceback (most recent call last):
  File "write_starfile.py", line 94, in <module>
    main(parse_args().parse_args())
  File "write_starfile.py", line 75, in main
    eulers = utils.R_to_relion_scipy(poses[0])
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/utils.py", line 128, in R_to_relion_scipy
    euler = RR.from_dcm(rot*f).as_euler('zxz', degrees=True)
AttributeError: type object 'scipy.spatial.transform.rotation.Rotation' has no attribute 'from_dcm'

It's the same poses.pkl file I used for training so I don't really know what's wrong.

Please let me know if you need anything else from me!

Thanks again,
Armando

**Comment by Guillawme** [comment]
Hello,

> Whenever I try to generate a .star file with filtered particles I only get a corrupt file that weights tops ~10 megabytes.

What makes you think the star file is corrupted? If it's only its size, it is normal that it is small because star files only contain information (in text form) about images, not the images themselves (they are in a corresponding mrcs file, as you noticed).

**Comment by ArmandoPach** [comment]
Hi Gauillawme!

Whenever I try to import a .star file that came from write_star.py (or even filter_star.py) I get an array error and blank field errors; this even when I reference the .mrc files just in case the relative path got broken (I've tried both referencing and not referencing).

This is not something that happens when I use translate_stack.py to go from .cs or .mrcs to .star (import of this .star file goes well!); it only happens whenever the --ind argument gets involved with a .star file (filtering a .mrcs does seem to work np).

I have then tried to change the .mrcs to a .star but I get the same problem with the resulting .star file. This is why I think there is something wrong with the file, although I have never scratched off the possibility of me doing something wrong/weird and I hope this is the case haha.

Thanks!
Armando

**Comment by zhonge** [comment]
Sorry about all the trouble. There is a scipy compatibility/deprecation issue -- it is also discussed here: https://github.com/zhonge/cryodrgn/issues/39

The solution is to use the current (v0.3.2b or later) version of the script `write_starfile.py`:
```
cd [path/to/repo]
git checkout 0.3.2b
python setup.py install
```

**Comment by ArmandoPach** [comment]
Hi,

I just made the utils.py change and the poses issue disappeared in write_starfile.py, thanks!

I was secretley hoping this would also fix my .star file issue but it's still buggy, do you think I might be doing something wrong?

Best,
Armando

**Comment by zhonge** [comment]
Hmm a bit hard to debug from afar. Can you provide the full command and output when you run write_starfile.py? 
It should print out the number of particles that are in the starfile -- I wonder if that the number that you are expecting?

**Comment by ArmandoPach** [comment]
Hi Ellen!

When using this command:

`python write_starfile.py /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/96Px/P16_J1536_particles/P16_J1536_particles_exported.cs /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/ctf.pkl --poses /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/poses.pkl --ind /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Trainings/HD_96_vae_01/Class1_Epoch_055.pkl --datadir /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/96Px/P16_J1536_particles/J1536/downsample/ --full-path -o /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/Class1_Epoch_055_96_Px.star`

I get the following message:

```
2021-05-27 21:08:13     785678 particles
2021-05-27 21:08:13     Filtering to 42181 particles
```

This looks normal given that 785,678 is my total particle number and 42,181 are the ones I want to keep. The output I get is the following: 

[Class1_Epoch_055_96_Px.zip](https://github.com/zhonge/cryodrgn/files/6557527/Class1_Epoch_055_96_Px.zip)

The particles, ctf, and poses files are exactly the ones I've used for training (the particles come from an exported cryoSPARC downsampling job).

I've opened the resulting .star file and compared it to other .star files that I know for sure work and the only things that I could see could be messing something up are the fact that they are referencing .mrc files instead of .mrcs files and that the particle indexing that doesn't have zeros infront like RELION .star files normally do but I am by no means an expert so I don't know.

I have tried importing the resulting .star particle to both RELION and cryoSPARC (making sure that the .mrc files are properley referenced) but in both I get error messages. RELION tells me the RELION 3.1 optics group issue and that it's referencing .mrc files instead of .mrcs files and cryoSPARC gives me reshaping array erros (it says it can't reshape an array of 0).

Thank you very much!
Armando

**Comment by zhonge** [comment]
Thanks for providing the star file, and sorry about the delay. Hmmm this is very strange. The starfile looks fine. I wonder if any of the .mrc files changed in the meanwhile? 

Could you try running cryoDRGN with that starfile? Something like:
```
cryodrgn train_nn Class1_Epoch_055_96_Px.star --ctf [path to ctf] --poses [path to poses] -n 1 -o test
```

**Comment by ArmandoPach** [comment]
Hi Ellen!

The .mrc files are the same ones used for training and have never been touched since I started using cryoDRGN. I exported the job from cryoSPARC, moved the whole exported directory to another place and started training with those particles.

I just ran the command you gave me and I got the following errors:

`(cryodrgn) $ cryodrgn train_nn /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/Class1_Epoch_055_96_Px.star --ctf /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/ctf.pkl --poses /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/poses.pkl -n 1 -o test
2021-06-07 15:14:52     /mnt/tesla/data/anaconda3/envs/cryodrgn/bin/cryodrgn train_nn /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/Class1_Epoch_055_96_Px.star --ctf /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/ctf.pkl --poses /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/poses.pkl -n 1 -o test
2021-06-07 15:14:52     Namespace(activation='relu', amp=False, batch_size=8, checkpoint=1, ctf='/mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/ctf.pkl', datadir=None, dim=256, do_pose_sgd=False, domain='fourier', emb_type='quat', func=<function main at 0x7f019a57b4d0>, ind=None, invert_data=True, l_extent=0.5, layers=3, lazy=False, load=None, log_interval=1000, lr=0.0001, multigpu=False, norm=None, num_epochs=1, outdir='/mnt/tesla/data/apalacios/cryoDRGN/utils/test', particles='/mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/Class1_Epoch_055_96_Px.star', pe_dim=None, pe_type='geom_lowf', pose_lr=0.0001, poses='/mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Parameters/poses.pkl', pretrain=5, relion31=False, seed=8163, verbose=False, wd=0, window=True)
2021-06-07 15:14:52     Use cuda True
Traceback (most recent call last):
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/dataset.py", line 25, in load_particles
    particles = starfile.Starfile.load(mrcs_txt_star, relion31=relion31).get_particles(datadir=datadir, lazy=lazy)
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/starfile.py", line 98, in get_particles
    dataset = np.array([x.get() for x in dataset])
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/starfile.py", line 98, in <listcomp>
    dataset = np.array([x.get() for x in dataset])
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/mrc.py", line 121, in get
    image = np.fromfile(f, dtype=self.dtype, count=np.product(self.shape)).reshape(self.shape)
ValueError: cannot reshape array of size 0 into shape (96,96)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/starfile.py", line 106, in prefix_paths
    assert os.path.exists(path)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.2', 'console_scripts', 'cryodrgn')())
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/__main__.py", line 52, in main
    args.func(args)
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/commands/train_nn.py", line 191, in main
    data = dataset.MRCData(args.particles, norm=args.norm, invert_data=args.invert_data, ind=ind, window=args.window, datadir=args.datadir, relion31=args.relion31)
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/dataset.py", line 100, in __init__
    particles_real = load_particles(mrcfile, False, datadir=datadir, relion31=relion31)
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/dataset.py", line 29, in load_particles
    particles = starfile.Starfile.load(mrcs_txt_star, relion31=relion31).get_particles(datadir=datadir, lazy=lazy)
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/starfile.py", line 90, in get_particles
    mrcs = prefix_paths(mrcs, datadir)
  File "/mnt/tesla/data/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/starfile.py", line 110, in prefix_paths
    assert os.path.exists(path), f'{path} not found'
AssertionError: /mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles//mnt/tesla/data/apalacios/cryoDRGN/45SYphC_Plus_YphC/Particles/96Px/P16_J1536_particles/J1536/downsample/batch_000325_downsample.mrc not found`

From what I can see I get the same array error I mentioned I get when I try to import the particles into cryoSPARC and also a referencing error that duplicates some part of the file path.

Thank you so much!
Armando
