### ISSUE TITLE
Compatibility with Expanse?

### ISSUE THREAD

**Issue by vinhbiochem** [zhonge/cryodrgn#67]
Hello! I'm interested in using cryodrgn with the XSEDE Expanse cluster, but am coming up with an error I was wondering if I could get some help with. After passing a train_vae command via slurm batch script, I get the following error:

```
Traceback (most recent call last):
  File "/home/vinht/.conda/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.2b0', 'console_scripts', 'cryodrgn')())
  File "/home/vinht/.conda/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/__main__.py", line 52, in main
    args.func(args)
  File "/home/vinht/.conda/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/commands/train_vae.py", line 411, in main
    for minibatch in data_generator:
  File "/home/vinht/.conda/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/vinht/.conda/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/vinht/.conda/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/vinht/.conda/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/home/vinht/.conda/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 124, in __iter__
    yield from torch.randperm(n, generator=generator).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```
I'm sure I'm using GPU's, but wasn't sure what to do about this error. Is there a way I can get around this?

**Comment by vinhbiochem** [comment]
Solved! Was a problem with my conda environment colliding with my loaded modules.
