### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by midauden** [zhonge/cryodrgn#74]
Hi
I am trying to run the cryoDRGN train using

cryodrgn train_vae -o train10/00_vae98 >> train9.00.log --zdim 8 --poses poses_j722.pkl --ctf ctf2_j722.pkl -n 50 --multigpu particles98.txt --relion31

 and got the following AssertionError

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-jphozp4m because the default path (/home/midauden/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/apps/miniconda3/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.2b0', 'console_scripts', 'cryodrgn')())
  File "/apps/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/__main__.py", line 52, in main
    args.func(args)
  File "/apps/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/commands/train_vae.py", line 345, in main
    enc_mask = lattice.get_circular_mask(args.enc_mask)
  File "/apps/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/lattice.py", line 76, in get_circular_mask
    assert self.coords[self.D**2//2].sum() == 0.0
AssertionError

Would you help me to fix it? Thanks a lot!
Maria

**Comment by midauden** [comment]
Thanks a lot! Now it works perfectly
