### ISSUE TITLE
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by qiliu-ghddi** [zhonge/cryodrgn#86]
Got the following RuntimeError when training CryoDRGN model (running `cryodrgn train_vae data/128/particles.128.mrcs  --ctf data/ctf.pkl  --poses data/poses.pkl  --zdim 8  -n 50  --uninvert-data -o tutorial/00_vae128 > tutorial_00.log`)

```shell
2021-11-09 09:37:23     Image size (pix)  : 128
2021-11-09 09:37:23     A/pix             : 3.2750000953674316
2021-11-09 09:37:23     DefocusU (A)      : 15301.099609375
2021-11-09 09:37:23     DefocusV (A)      : 14916.400390625
2021-11-09 09:37:23     Dfang (deg)       : 5.28000020980835
2021-11-09 09:37:23     voltage (kV)      : 300.0
2021-11-09 09:37:23     cs (mm)           : 2.700000047683716
2021-11-09 09:37:23     w                 : 0.07000000029802322
2021-11-09 09:37:23     Phase shift (deg) : 0.0
2021-11-09 09:37:23     Using circular lattice with radius 64
2021-11-09 09:37:24     HetOnlyVAE(
  (encoder): ResidLinearMLP(
    (main): Sequential(
      (0): Linear(in_features=12852, out_features=256, bias=True)
      (1): ReLU()
      (2): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (3): ReLU()
      (4): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (5): ReLU()
      (6): ResidLinear(
        (linear): Linear(in_features=256, out_features=256, bias=True)
      )
      (7): ReLU()
      (8): Linear(in_features=256, out_features=16, bias=True)
    )
  )
  (decoder): FTPositionalDecoder(
    (decoder): ResidLinearMLP(
      (main): Sequential(
        (0): Linear(in_features=392, out_features=256, bias=True)
        (1): ReLU()
        (2): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (3): ReLU()
        (4): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (5): ReLU()
        (6): ResidLinear(
          (linear): Linear(in_features=256, out_features=256, bias=True)
        )
        (7): ReLU()
        (8): Linear(in_features=256, out_features=2, bias=True)
      )
    )
  )
)
2021-11-09 09:37:24     3790354 parameters in model
2021-11-09 09:37:24     3491856 parameters in encoder
2021-11-09 09:37:24     298498 parameters in decoder
Traceback (most recent call last):
  File "/home/qiliu/miniconda3/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.2b0', 'console_scripts', 'cryodrgn')())
  File "/home/qiliu/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/__main__.py", line 52, in main
    args.func(args)
  File "/home/qiliu/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/commands/train_vae.py", line 411, in main
    for minibatch in data_generator:
  File "/home/qiliu/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/qiliu/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 556, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/qiliu/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/qiliu/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/qiliu/miniconda3/envs/cryodrgn/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 125, in __iter__
    yield from torch.randperm(n, generator=self.generator).tolist()
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal
```

**Comment by qiliu-ghddi** [comment]
The version of pytorch is `1.8.0` and the version of CUDA  is `11.1` , 
```
(cryodrgn) $ python -c "import torch; print(torch.__version__)"
1.8.0+cu111
(cryodrgn) $ python -c "import torch; print(torch.version.cuda)"
11.1
```

It seems that it is [a bug of PyTorch 1.8.0](https://github.com/pytorch/pytorch/issues/54245).

**Comment by qiliu-ghddi** [comment]
[Having the same issue with pytorch 1.8.1 and cuda 11.1.](https://discuss.pytorch.org/t/pytorch-1-8-0-fasterrcnn-resnet50-fpn-error/114150/9)

**Comment by zhonge** [comment]
I'm seeing [here](https://github.com/facebookresearch/detectron2/issues/2743) that the solution may be to downgrade to pytorch 1.7. It may also have something to do with a mismatched cuda version in your install. You can check your cuda version with `nvidia-smi`.

**Comment by Guillawme** [comment]
Note that under certain circumstances, `nvidia-smi` will not report the version of CUDA actually in use. It always reports the CUDA version that was distributed by Nvidia with the driver version installed on the system. But in conda environments, you may get a `cudatoolkit` package with a different version of CUDA. You can also install any specific version of CUDA that you then load into your environment (for example with the environment modules system), which will appear from this shell session as the only CUDA version (and will indeed be the one in use), but `nvidia-smi` will still report the same CUDA version as it always does.

For example on my system, `nvidia-smi` always says I have CUDA 11.5, even if I change my environment to make CUDA 10.2 the default version for this shell session (see below).

```
$ nvidia-smi
Tue Nov  9 15:18:58 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
...

$ which nvcc
/usr/bin/which: no nvcc in path

$ module load cuda/10.2

$ which nvcc
/opt/cuda-10.2/bin/nvcc

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

$ nvidia-smi
Tue Nov  9 15:21:08 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
...
```

**Comment by qiliu-ghddi** [comment]
> I'm seeing [here](https://github.com/facebookresearch/detectron2/issues/2743) that the solution may be to downgrade to pytorch 1.7. It may also have something to do with a mismatched cuda version in your install. You can check your cuda version with `nvidia-smi`.

Yes, I solve this problem by reinstalling **CUDA 10.2** and downgrading PyTorch to v1.7.1.

**Comment by zhonge** [comment]
Excellent. Thanks for reporting.
